# list of keywords

## Keywords Generated from Google Keyword Planner
keywords = [
    "AI Advertising",
    "AI Analytics",
    "AI Applications",
    "AI App",
    "AI Assistant",
    "AI Automation",
    "AI Bot",
    "AI Chat",
    "AI Chat Bot",
    "AI Chatbots",
    "AI ChatGPT",
    "AI Cloud",
    "AI Completion",
    "AI Conversation Bot",
    "AI Conversational",
    "AI Data",
    "AI Deep Learning",
    "AI Driven",
    "AI Enterprise",
    "AI Free Chat",
    "AI GBT",
    "AI General",
    "AI Girlfriend Chat",
    "AI GPU",
    "AI GPT",
    "AI Intelligence",
    "AI Language Model",
    "AI Learning",
    "AI Machine Learning",
    "AI Messaging",
    "AI ML",
    "AI Models",
    "AI NLP",
    "AI Open Chat",
    "AI Open Source",
    "AI Personal Assistant",
    "AI Predictive",
    "AI Program",
    "AI Services",
    "AI Tech",
    "AI Text Generation",
    "AI Text Generation Completion",
    "AI Tools",
    "AI Virtual Assistant",
    "AI Watson",
    "Amazon AI",
    "API Chatbot",
    "API Development",
    "API Integration",
    "API Management",
    "API Services",
    "API Testing",
    "Apple AI",
    "Artificial AI",
    "Artificial General Intelligence",
    "Artificial Intelligence",
    "Artificial Intelligence AI",
    "Artificial Intelligence Article",
    "Artificial Intelligence Deep Learning",
    "Artificial Intelligence GPT",
    "Artificial Intelligence Learning",
    "AWS AI",
    "Baidu AI",
    "Bards AI",
    "BERT",
    "Big Data AI",
    "Bing AI",
    "Bing AI Chat",
    "Bing Chatbot",
    "Bot AI Chat",
    "C3 AI",
    "Chad GBT",
    "Chapt GPT AI",
    "Character AI Chatbot",
    "Chat Bot",
    "Chat GPT",
    "Chat GPT 3",
    "Chat GPT AI",
    "Chat GPT App",
    "Chat GPT Artificial Intelligence",
    "Chat GPT Bot",
    "Chat GPT Cloud",
    "Chat GPT Free",
    "Chat GPT Language Models",
    "Chat GPT Large Language Models",
    "Chat GPT Model",
    "Chat GPT Open AI",
    "Chat GPT Search",
    "Chat GPT Virtual Assistant",
    "Chat Open AI",
    "Chatbot",
    "Chatbot AI",
    "Chatbot Developer",
    "Claude",
    "Cloud AI",
    "Cloud API",
    "Conversational AI",
    "Coursera Artificial Intelligence",
    "Customer Service Bot",
    "Deep Learning AI",
    "DeepMind AI",
    "Discord AI Bot",
    "Doc AI",
    "Elon Musk AI",
    "Facebook Chat Bot",
    "Finance AI",
    "Free AI",
    "Free AI Chatbot",
    "Free Chat AI",
    "Free ChatGPT",
    "Free GPT",
    "General AI",
    "Generative AI",
    "GPT",
    "GPT 2",
    "GPT 3",
    "GPT 3.5",
    "GPT 4",
    "GPT 5",
    "GPT Chat AI",
    "GPT Chatbot",
    "GraphQL API",
    "Human AI",
    "IBM AI",
    "Inflection AI",
    "Intel AI",
    "Language Model",
    "Language Models AI",
    "Large Language Model",
    "Large Language Model AI",
    "Large Language Model LLM",
    "Large Language Models",
    "Large Transformer Models",
    "Leonardo AI",
    "LLM AI",
    "LLM GPT",
    "Machine Learning",
    "Machine Learning Language Models",
    "Massive Language Models",
    "Meta AI",
    "Meta Language Model",
    "Meta Large Language Models",
    "Meta OPT 175",
    "Microsoft AI",
    "Microsoft Bing AI",
    "Microsoft Chatbot AI",
    "Natural Language Processing AI",
    "Nvidia AI",
    "Nvidia AI GPU",
    "Open AI",
    "Open AI Chat",
    "Open AI Chatbot",
    "Open AI ChatGPT",
    "Open GPT",
    "Open Source AI",
    "Open Source Language Models",
    "Open Source LLM",
    "Oracle AI",
    "Personal AI",
    "Power AI",
    "Predictive AI",
    "Python AI",
    "Raspberry Pi AI",
    "Siri AI",
    "Small Language Model",
    "Stuart Russell",
    "Super AI",
    "Tesla AI",
    "Text Generation",
    "Text Generation AI",
    "Transformer Model",
    "Unity AI",
    "Use Chat GPT",
    "Vertex AI",
    "Virtual Assistant AI",
    "Watson AI",
    "WhatsApp AI Chatbot",
    "Zendesk Chat Bot"
]

country_codes = {
    "United States": "us",
    "Afghanistan": "af",
    "Algeria": "dz",
    "Angola": "ao",
    "Argentina": "ar",
    "Australia": "au",
    "Austria": "at",
    "Bangladesh": "bd",
    "Belarus": "by",
    "Belgium": "be",
    "Belize":  "bz",
    "Bolivia": "bo",
    "Bosnia And Herzegovina": "ba",
    "Botswana": "bw",
    "Brazil": "br",
    "Bulgaria": "bg",
    "Cambodia": "kh",
    "Cameroon": "cm",
    "Canada": "ca",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Congo": "cd",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Cyprus": "cy",
    "Czech Republic": "cz",
    "Côte D'Ivoire": "ci",
    "Denmark": "dk",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "Estonia": "ee",
    "Finland": "fi",
    "France": "fr",
    "Gabon": "ga",
    "Georgia": "ge",
    "Germany": "de",
    "Greece": "gr",
    "Guatemala": "gt",
    "Honduras": "hn",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Iran": "ir",
    "Iraq": "iq",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Japan": "jp",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Korea": "kr",
    "Kosovo": "xk",
    "Kuwait": "kw",
    "Laos": "la",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Libya": "ly",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Macao": "mo",
    "Malawi": "mw",
    "Malaysia": "my",
    "Maldives": "mv",
    "Mexico": "mx",
    "Montenegro": "me",
    "Morocco": "ma",
    "Myanmar": "mm",
    "Nauru": "nr",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Nigeria": "ng",
    "Norway": "no",
    "Oman": "om",
    "Pakistan": "pk",
    "Panama": "pa",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Romania": "ro",
    "Russia": "ru",
    "Rwanda": "rw",
    "Saudi Arabia": "sa",
    "Senegal": "sn",
    "Serbia": "rs",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "South Africa": "za",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sweden": "se",
    "Switzerland": "ch",
    "Taiwan": "tw",
    "Tanzania": "tz",
    "Thailand": "th",
    "Tonga": "to",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "Uruguay": "uy",
    "Vanuatu": "vu",
    "Venezuela": "ve",
    "Vietnam": "vn",
    "Zambia": "zm",
    "Zimbabwe": "zw"
    }